<?php

use SegmentGenerator\App\Application;
use SegmentGenerator\App\CLIGeneratorSettings;
use SegmentGenerator\App\SettableFacade;

require __DIR__ . '/vendor/autoload.php';

/**
 * The convention.
 *
 * The silence is a duration of an empty sound. They are taken from a XML file.
 * The chapter part is a duration with a sound that generated by silences. It has an offset from a last part. It can have side silences.
 * The chapter is a collection with chapter parts. It can have its own title.
 * The chapter collection is a complited book that contains chapters.
 * The segment is grouped parts of a chapter that has an offset from a last segment.
 */

$settings = new CLIGeneratorSettings;
$facade = new SettableFacade($settings);
$app = new Application($facade);
$app->run();
